### ISSUE TITLE
OGRIP LBRS (Ohio)

### ISSUE THREAD

**Issue by 1ec5** [osmlab/centerlines#24]
[OGRIP LBRS](http://ogrip.oit.ohio.gov/projectsinitiatives/lbrs.aspx):

> The Location Based Response System (LBRS) is an initiative of the Ohio Geographically Referenced Information Program (OGRIP). The LBRS establishes partnerships between State and County government for the creation of spatially accurate street centerlines with address ranges and field verified site-specific address locations.

[White paper](http://gis3.oit.ohio.gov/LBRS/_downloads/docs/White%20Paper-LBRS_2011.pdf#page=4):

> Because it is field verified, all LBRS data boasts positional accuracy to +/-1 meter.
> All information placed in the LBRS is public domain.
> Participation in the LBRS program is completely voluntary, yet 75 of the 88 counties in Ohio have chosen to participate thus far. Of the remaining 13 counties, more than half have expressed some level of interest in joining the program.

[Downloads](http://gis3.oit.ohio.gov/geodatadownload/lbrs.aspx)

/cc @skorasaurus

**Comment by skorasaurus** [comment]
Regarding licensing, they are in the Public Domain; I've emailed the state in 2015; their response is at https://github.com/openaddresses/openaddresses/issues/103

**Comment by 1ec5** [comment]
#26 adds OGRIP LBRS for 82 counties.
