### ISSUE TITLE
New York City, NY

### ISSUE THREAD

**Issue by tmorrisseyNYC** [osmlab/centerlines#6]
NYC Street Centerline (CSCL)
[https://data.cityofnewyork.us/resource/67bu-uj7m.json](https://data.cityofnewyork.us/resource/67bu-uj7m.json)

EDIT: URL

**Comment by talllguy** [comment]
Is [this](https://data.cityofnewyork.us/City-Government/NYC-Street-Centerline-CSCL-/exjm-f27b) the same dataset? That json crashed my browser :joy: :floppy_disk:

**Comment by talllguy** [comment]
If yes, here's a sample of the attributes for reference.

| attribute | value |
| --- | --- |
| borocode | 2 |
| created | 2007-11-29T00:00:00.000Z |
| frm_lvl_co | 13 |
| l_blkfc_id | 1522603182 |
| l_high_hn | 64 |
| l_low_hn | 30 |
| l_zip | 10452 |
| modified | 2015-12-22T00:00:00.000Z |
| physicalid | 87311 |
| r_blkfc_id | 1522603027 |
| r_high_hn | 59 |
| r_low_hn | 30 |
| r_zip | 10452 |
| rw_type | 1 |
| shape_leng | 471.205206667 |
| snow_pri | P |
| st_name | FEATHERBED LA |
| st_width | 42 |
| status | 2 |
| to_lvl_co | 13 |
| trafdir | TW |
